services:
  mysql:
    container_name: ${PROJECT_ALIAS}_mysql
    image: "mariadb:10.2"
    volumes:
      - ${PROJECT_MYSQL_DIR}:/var/lib/mysql
    ports:
      - "${MYSQL_PORT}:3306"
    environment:
      MYSQL_DATABASE: ${MYSQL_DB}
      MYSQL_ROOT_PASSWORD: "${MYSQL_PASSWORD}"

  phpmyadmin:
    container_name: ${PROJECT_ALIAS}_pma
    image: phpmyadmin/phpmyadmin
    links:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_USER: ${MYSQL_USER}
      PMA_PASSWORD: "${MYSQL_PASSWORD}"
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - ${PHPMYADMIN_PORT}:80

  wordpress:
    container_name: ${PROJECT_ALIAS}_wp
    build:
      context: ./.docker
      dockerfile: WPDockerfile
    ports:
      - "${WP_PORT}:80"
    links:
      - mysql
    volumes:
      - ${PROJECT_WP_DIR}:${WP_DIR}:rw
      - ./.docker/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
    environment:
      WORDPRESS_DB_HOST: mysql
      WORDPRESS_DB_USER: ${MYSQL_USER}
      WORDPRESS_DB_PASSWORD: "${MYSQL_PASSWORD}"
      WORDPRESS_DB_NAME: ${MYSQL_DB}
      WORDPRESS_TABLE_PREFIX: ${PROJECT_ALIAS}_
      WORDPRESS_DEBUG: true
    extra_hosts:
      - "host.docker.internal:host-gateway"